apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: my-nginx
        image: nginx
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        # env:
        # - name: GET_HOSTS_FROM
        #   value: dns
        #   # Using `GET_HOSTS_FROM=dns` requires your cluster to
        #   # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
        #   # service launched automatically. However, if the cluster you are using
        #   # does not have a built-in DNS service, you can instead
        #   # access an environment variable to find the master
        #   # service's host. To do so, comment out the 'value: dns' line above, and
        #   # uncomment the line below:
        #   # value: env
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: my-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: frontend-pod
